// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerritoryWeb.Data.Database;

#nullable disable

namespace Data.Database.Migrations
{
    [DbContext(typeof(TerritoryWebDbContext))]
    partial class TerritoryWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TerritoryWeb.Data.Models.Congregation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Congregations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cedar Crest Spanish"
                        });
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DoorCodeID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("GeoLat")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("GeoLong")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<int?>("LanguageID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerritoryID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoorCodeID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("TerritoryID");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.DoorCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CongregationID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CongregationID");

                    b.ToTable("DoorCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CongregationID = 1,
                            Description = "Expulsado"
                        },
                        new
                        {
                            Id = 2,
                            CongregationID = 1,
                            Description = "Peligroso"
                        },
                        new
                        {
                            Id = 3,
                            CongregationID = 1,
                            Description = "No Visitar"
                        },
                        new
                        {
                            Id = 4,
                            CongregationID = 1,
                            Description = "Privado"
                        },
                        new
                        {
                            Id = 5,
                            CongregationID = 1,
                            Description = "Vacio"
                        },
                        new
                        {
                            Id = 6,
                            CongregationID = 1,
                            Description = "Negocio"
                        },
                        new
                        {
                            Id = 7,
                            CongregationID = 1,
                            Description = "No desean cartas"
                        });
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CongregationID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CongregationID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "English"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Español"
                        });
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.PublisherType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PublisherTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Publisher"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pioneer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Elder"
                        });
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.Territory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedPublisherID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CheckedIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckedOut")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CongregationID")
                        .HasColumnType("int");

                    b.Property<string>("LastCheckedInBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TerritoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerritoryTypeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CongregationID");

                    b.HasIndex("TerritoryTypeID");

                    b.ToTable("Territories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Added = new DateTime(2023, 3, 13, 10, 49, 53, 736, DateTimeKind.Local).AddTicks(2564),
                            AddedBy = "cyberyaga@hotmail.com",
                            AssignedPublisherID = "",
                            City = "",
                            CongregationID = 1,
                            LastCheckedInBy = "",
                            Modified = new DateTime(2023, 3, 13, 10, 49, 53, 736, DateTimeKind.Local).AddTicks(2611),
                            ModifiedBy = "cyberyaga@hotmail.com",
                            Notes = "",
                            TerritoryName = "Allentown - 01",
                            TerritoryTypeID = 1
                        });
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.TerritoryAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWrite")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TempAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TerritoryID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryID");

                    b.ToTable("TerritoryAccess");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.TerritoryBound", b =>
                {
                    b.Property<int>("BoundaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("GeoLat")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("GeoLong")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<int>("TerritoryID")
                        .HasColumnType("int");

                    b.HasKey("BoundaryID");

                    b.HasIndex("TerritoryID");

                    b.ToTable("TerritoryBounds");

                    b.HasData(
                        new
                        {
                            BoundaryID = 2430,
                            GeoLat = 40.584240m,
                            GeoLong = -75.503010m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2431,
                            GeoLat = 40.579930m,
                            GeoLong = -75.502500m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2432,
                            GeoLat = 40.578870m,
                            GeoLong = -75.502400m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2433,
                            GeoLat = 40.577780m,
                            GeoLong = -75.502280m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2434,
                            GeoLat = 40.577100m,
                            GeoLong = -75.502200m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2435,
                            GeoLat = 40.576790m,
                            GeoLong = -75.502170m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2436,
                            GeoLat = 40.576520m,
                            GeoLong = -75.502080m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2437,
                            GeoLat = 40.576260m,
                            GeoLong = -75.501960m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2438,
                            GeoLat = 40.575890m,
                            GeoLong = -75.501690m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2439,
                            GeoLat = 40.575550m,
                            GeoLong = -75.501410m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2440,
                            GeoLat = 40.575070m,
                            GeoLong = -75.501010m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2441,
                            GeoLat = 40.574470m,
                            GeoLong = -75.500530m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2442,
                            GeoLat = 40.574220m,
                            GeoLong = -75.500240m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2443,
                            GeoLat = 40.574080m,
                            GeoLong = -75.500020m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2444,
                            GeoLat = 40.573890m,
                            GeoLong = -75.499710m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2445,
                            GeoLat = 40.573600m,
                            GeoLong = -75.499350m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2446,
                            GeoLat = 40.573350m,
                            GeoLong = -75.499170m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2447,
                            GeoLat = 40.573070m,
                            GeoLong = -75.499030m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2448,
                            GeoLat = 40.572670m,
                            GeoLong = -75.498960m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2449,
                            GeoLat = 40.572510m,
                            GeoLong = -75.498980m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2450,
                            GeoLat = 40.572370m,
                            GeoLong = -75.499000m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2451,
                            GeoLat = 40.571590m,
                            GeoLong = -75.499210m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2452,
                            GeoLat = 40.571050m,
                            GeoLong = -75.499350m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2453,
                            GeoLat = 40.570610m,
                            GeoLong = -75.499450m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2454,
                            GeoLat = 40.570320m,
                            GeoLong = -75.499470m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2455,
                            GeoLat = 40.570070m,
                            GeoLong = -75.499470m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2456,
                            GeoLat = 40.569860m,
                            GeoLong = -75.499460m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2457,
                            GeoLat = 40.569500m,
                            GeoLong = -75.499390m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2458,
                            GeoLat = 40.569210m,
                            GeoLong = -75.499300m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2459,
                            GeoLat = 40.568420m,
                            GeoLong = -75.498920m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2460,
                            GeoLat = 40.567320m,
                            GeoLong = -75.498280m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2461,
                            GeoLat = 40.566620m,
                            GeoLong = -75.497890m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2462,
                            GeoLat = 40.565930m,
                            GeoLong = -75.497500m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2463,
                            GeoLat = 40.564660m,
                            GeoLong = -75.484860m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2464,
                            GeoLat = 40.571450m,
                            GeoLong = -75.481290m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2465,
                            GeoLat = 40.571880m,
                            GeoLong = -75.481070m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2466,
                            GeoLat = 40.572390m,
                            GeoLong = -75.480890m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2467,
                            GeoLat = 40.572760m,
                            GeoLong = -75.480830m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2468,
                            GeoLat = 40.574330m,
                            GeoLong = -75.480820m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2469,
                            GeoLat = 40.575870m,
                            GeoLong = -75.480840m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2470,
                            GeoLat = 40.577110m,
                            GeoLong = -75.480830m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2471,
                            GeoLat = 40.577620m,
                            GeoLong = -75.480820m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2472,
                            GeoLat = 40.578170m,
                            GeoLong = -75.480810m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2473,
                            GeoLat = 40.578670m,
                            GeoLong = -75.480700m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2474,
                            GeoLat = 40.578800m,
                            GeoLong = -75.480670m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2475,
                            GeoLat = 40.578910m,
                            GeoLong = -75.480610m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2476,
                            GeoLat = 40.579130m,
                            GeoLong = -75.480510m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2477,
                            GeoLat = 40.579340m,
                            GeoLong = -75.480420m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2478,
                            GeoLat = 40.579570m,
                            GeoLong = -75.480310m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2479,
                            GeoLat = 40.579910m,
                            GeoLong = -75.480080m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2480,
                            GeoLat = 40.580170m,
                            GeoLong = -75.479850m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2481,
                            GeoLat = 40.580360m,
                            GeoLong = -75.479640m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2482,
                            GeoLat = 40.580410m,
                            GeoLong = -75.479590m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2483,
                            GeoLat = 40.580550m,
                            GeoLong = -75.479430m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2484,
                            GeoLat = 40.580630m,
                            GeoLong = -75.479350m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2485,
                            GeoLat = 40.580700m,
                            GeoLong = -75.479260m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2486,
                            GeoLat = 40.580860m,
                            GeoLong = -75.479100m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2487,
                            GeoLat = 40.581040m,
                            GeoLong = -75.478900m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2488,
                            GeoLat = 40.581130m,
                            GeoLong = -75.478800m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2489,
                            GeoLat = 40.581270m,
                            GeoLong = -75.478650m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2490,
                            GeoLat = 40.581410m,
                            GeoLong = -75.478490m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2491,
                            GeoLat = 40.581550m,
                            GeoLong = -75.478340m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2492,
                            GeoLat = 40.581600m,
                            GeoLong = -75.478290m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2493,
                            GeoLat = 40.581750m,
                            GeoLong = -75.478120m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2494,
                            GeoLat = 40.581790m,
                            GeoLong = -75.478070m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2495,
                            GeoLat = 40.581830m,
                            GeoLong = -75.478030m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2496,
                            GeoLat = 40.581870m,
                            GeoLong = -75.477980m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2497,
                            GeoLat = 40.581920m,
                            GeoLong = -75.477940m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2498,
                            GeoLat = 40.581950m,
                            GeoLong = -75.477900m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2499,
                            GeoLat = 40.581990m,
                            GeoLong = -75.477850m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2500,
                            GeoLat = 40.582070m,
                            GeoLong = -75.477770m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2501,
                            GeoLat = 40.582180m,
                            GeoLong = -75.477650m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2502,
                            GeoLat = 40.582290m,
                            GeoLong = -75.477520m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2503,
                            GeoLat = 40.582340m,
                            GeoLong = -75.477610m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2504,
                            GeoLat = 40.582380m,
                            GeoLong = -75.477680m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2505,
                            GeoLat = 40.582480m,
                            GeoLong = -75.477840m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2506,
                            GeoLat = 40.582610m,
                            GeoLong = -75.478030m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2507,
                            GeoLat = 40.582670m,
                            GeoLong = -75.478110m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2508,
                            GeoLat = 40.582740m,
                            GeoLong = -75.478200m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2509,
                            GeoLat = 40.582890m,
                            GeoLong = -75.478340m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2510,
                            GeoLat = 40.583040m,
                            GeoLong = -75.478470m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2511,
                            GeoLat = 40.583150m,
                            GeoLong = -75.478550m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2512,
                            GeoLat = 40.583260m,
                            GeoLong = -75.478630m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2513,
                            GeoLat = 40.583280m,
                            GeoLong = -75.478650m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2514,
                            GeoLat = 40.583330m,
                            GeoLong = -75.478740m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2515,
                            GeoLat = 40.583390m,
                            GeoLong = -75.478820m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2516,
                            GeoLat = 40.583530m,
                            GeoLong = -75.478800m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2517,
                            GeoLat = 40.583680m,
                            GeoLong = -75.478780m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2518,
                            GeoLat = 40.583950m,
                            GeoLong = -75.478740m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2519,
                            GeoLat = 40.584100m,
                            GeoLong = -75.478740m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2520,
                            GeoLat = 40.584280m,
                            GeoLong = -75.478750m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2521,
                            GeoLat = 40.584490m,
                            GeoLong = -75.478780m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2522,
                            GeoLat = 40.584720m,
                            GeoLong = -75.478830m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2523,
                            GeoLat = 40.585090m,
                            GeoLong = -75.478880m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2524,
                            GeoLat = 40.585300m,
                            GeoLong = -75.478910m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2525,
                            GeoLat = 40.585520m,
                            GeoLong = -75.478940m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2526,
                            GeoLat = 40.585490m,
                            GeoLong = -75.479060m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2527,
                            GeoLat = 40.585480m,
                            GeoLong = -75.479190m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2528,
                            GeoLat = 40.585510m,
                            GeoLong = -75.479260m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2529,
                            GeoLat = 40.585530m,
                            GeoLong = -75.479300m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2530,
                            GeoLat = 40.585550m,
                            GeoLong = -75.479350m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2531,
                            GeoLat = 40.585730m,
                            GeoLong = -75.479610m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2532,
                            GeoLat = 40.585930m,
                            GeoLong = -75.479910m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2533,
                            GeoLat = 40.586170m,
                            GeoLong = -75.480270m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2534,
                            GeoLat = 40.586390m,
                            GeoLong = -75.480600m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2535,
                            GeoLat = 40.586560m,
                            GeoLong = -75.480860m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2536,
                            GeoLat = 40.586660m,
                            GeoLong = -75.481010m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2537,
                            GeoLat = 40.586890m,
                            GeoLong = -75.481380m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2538,
                            GeoLat = 40.587090m,
                            GeoLong = -75.481670m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2539,
                            GeoLat = 40.587340m,
                            GeoLong = -75.482060m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2540,
                            GeoLat = 40.587650m,
                            GeoLong = -75.482540m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2541,
                            GeoLat = 40.587900m,
                            GeoLong = -75.482910m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2542,
                            GeoLat = 40.588140m,
                            GeoLong = -75.483270m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2543,
                            GeoLat = 40.588230m,
                            GeoLong = -75.483380m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2544,
                            GeoLat = 40.588300m,
                            GeoLong = -75.483500m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2545,
                            GeoLat = 40.588360m,
                            GeoLong = -75.483600m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2546,
                            GeoLat = 40.588380m,
                            GeoLong = -75.483660m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2547,
                            GeoLat = 40.588410m,
                            GeoLong = -75.483720m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2548,
                            GeoLat = 40.588490m,
                            GeoLong = -75.483990m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2549,
                            GeoLat = 40.588580m,
                            GeoLong = -75.484400m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2550,
                            GeoLat = 40.588590m,
                            GeoLong = -75.484890m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2551,
                            GeoLat = 40.588470m,
                            GeoLong = -75.486060m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2552,
                            GeoLat = 40.588410m,
                            GeoLong = -75.486710m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2553,
                            GeoLat = 40.588420m,
                            GeoLong = -75.486980m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2554,
                            GeoLat = 40.588460m,
                            GeoLong = -75.487240m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2555,
                            GeoLat = 40.588600m,
                            GeoLong = -75.487560m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2556,
                            GeoLat = 40.588830m,
                            GeoLong = -75.487770m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2557,
                            GeoLat = 40.589100m,
                            GeoLong = -75.487880m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2558,
                            GeoLat = 40.589370m,
                            GeoLong = -75.488030m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2559,
                            GeoLat = 40.589680m,
                            GeoLong = -75.488160m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2560,
                            GeoLat = 40.590000m,
                            GeoLong = -75.488330m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2561,
                            GeoLat = 40.589930m,
                            GeoLong = -75.488530m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2562,
                            GeoLat = 40.589850m,
                            GeoLong = -75.488720m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2563,
                            GeoLat = 40.589700m,
                            GeoLong = -75.489040m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2564,
                            GeoLat = 40.589550m,
                            GeoLong = -75.489350m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2565,
                            GeoLat = 40.589390m,
                            GeoLong = -75.489680m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2566,
                            GeoLat = 40.589320m,
                            GeoLong = -75.489840m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2567,
                            GeoLat = 40.589250m,
                            GeoLong = -75.490010m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2568,
                            GeoLat = 40.589180m,
                            GeoLong = -75.490250m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2569,
                            GeoLat = 40.589130m,
                            GeoLong = -75.490480m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2570,
                            GeoLat = 40.589070m,
                            GeoLong = -75.491090m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2571,
                            GeoLat = 40.589030m,
                            GeoLong = -75.491450m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2572,
                            GeoLat = 40.588980m,
                            GeoLong = -75.491910m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2573,
                            GeoLat = 40.588950m,
                            GeoLong = -75.492100m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2574,
                            GeoLat = 40.588920m,
                            GeoLong = -75.492300m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2575,
                            GeoLat = 40.588890m,
                            GeoLong = -75.492490m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2576,
                            GeoLat = 40.588840m,
                            GeoLong = -75.492680m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2577,
                            GeoLat = 40.588780m,
                            GeoLong = -75.492890m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2578,
                            GeoLat = 40.588730m,
                            GeoLong = -75.493030m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2579,
                            GeoLat = 40.588640m,
                            GeoLong = -75.493260m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2580,
                            GeoLat = 40.588400m,
                            GeoLong = -75.493770m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2581,
                            GeoLat = 40.588230m,
                            GeoLong = -75.494110m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2582,
                            GeoLat = 40.588050m,
                            GeoLong = -75.494480m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2583,
                            GeoLat = 40.587890m,
                            GeoLong = -75.494800m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2584,
                            GeoLat = 40.587730m,
                            GeoLong = -75.495120m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2585,
                            GeoLat = 40.587570m,
                            GeoLong = -75.495400m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2586,
                            GeoLat = 40.587410m,
                            GeoLong = -75.495660m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2587,
                            GeoLat = 40.587260m,
                            GeoLong = -75.495870m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2588,
                            GeoLat = 40.587180m,
                            GeoLong = -75.495990m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2589,
                            GeoLat = 40.587110m,
                            GeoLong = -75.496110m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2590,
                            GeoLat = 40.587020m,
                            GeoLong = -75.496310m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2591,
                            GeoLat = 40.586940m,
                            GeoLong = -75.496510m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2592,
                            GeoLat = 40.586860m,
                            GeoLong = -75.496770m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2593,
                            GeoLat = 40.586790m,
                            GeoLong = -75.497000m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2594,
                            GeoLat = 40.586610m,
                            GeoLong = -75.497600m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2595,
                            GeoLat = 40.586510m,
                            GeoLong = -75.497890m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2596,
                            GeoLat = 40.586410m,
                            GeoLong = -75.498210m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2597,
                            GeoLat = 40.586280m,
                            GeoLong = -75.498650m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2598,
                            GeoLat = 40.586190m,
                            GeoLong = -75.498890m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2599,
                            GeoLat = 40.586060m,
                            GeoLong = -75.499170m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2600,
                            GeoLat = 40.585920m,
                            GeoLong = -75.499430m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2601,
                            GeoLat = 40.585780m,
                            GeoLong = -75.499610m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2602,
                            GeoLat = 40.585650m,
                            GeoLong = -75.499780m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2603,
                            GeoLat = 40.585370m,
                            GeoLong = -75.500110m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2604,
                            GeoLat = 40.585110m,
                            GeoLong = -75.500400m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2605,
                            GeoLat = 40.584870m,
                            GeoLong = -75.500660m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2606,
                            GeoLat = 40.584750m,
                            GeoLong = -75.500820m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2607,
                            GeoLat = 40.584660m,
                            GeoLong = -75.500970m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2608,
                            GeoLat = 40.584580m,
                            GeoLong = -75.501080m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2609,
                            GeoLat = 40.584530m,
                            GeoLong = -75.501210m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2610,
                            GeoLat = 40.584480m,
                            GeoLong = -75.501330m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2611,
                            GeoLat = 40.584430m,
                            GeoLong = -75.501470m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2612,
                            GeoLat = 40.584400m,
                            GeoLong = -75.501590m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2613,
                            GeoLat = 40.584370m,
                            GeoLong = -75.501700m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2614,
                            GeoLat = 40.584340m,
                            GeoLong = -75.501820m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2615,
                            GeoLat = 40.584320m,
                            GeoLong = -75.501950m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2616,
                            GeoLat = 40.584300m,
                            GeoLong = -75.502240m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2617,
                            GeoLat = 40.584280m,
                            GeoLong = -75.502550m,
                            TerritoryID = 1
                        },
                        new
                        {
                            BoundaryID = 2618,
                            GeoLat = 40.584240m,
                            GeoLong = -75.503010m,
                            TerritoryID = 1
                        });
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.TerritoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TerritoryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Door to Door"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Telephone"
                        });
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.URLMinimizeStore", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("longURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("shortURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("used")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("URLMinimizeStore");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.Door", b =>
                {
                    b.HasOne("TerritoryWeb.Data.Models.DoorCode", "DoorCode")
                        .WithMany()
                        .HasForeignKey("DoorCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerritoryWeb.Data.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerritoryWeb.Data.Models.Territory", "Territory")
                        .WithMany()
                        .HasForeignKey("TerritoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoorCode");

                    b.Navigation("Language");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.DoorCode", b =>
                {
                    b.HasOne("TerritoryWeb.Data.Models.Congregation", "Congregation")
                        .WithMany("DoorCodes")
                        .HasForeignKey("CongregationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Congregation");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.Language", b =>
                {
                    b.HasOne("TerritoryWeb.Data.Models.Congregation", "Congregation")
                        .WithMany()
                        .HasForeignKey("CongregationID");

                    b.Navigation("Congregation");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.Territory", b =>
                {
                    b.HasOne("TerritoryWeb.Data.Models.Congregation", "Congregation")
                        .WithMany()
                        .HasForeignKey("CongregationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerritoryWeb.Data.Models.TerritoryType", "TerritoryType")
                        .WithMany()
                        .HasForeignKey("TerritoryTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Congregation");

                    b.Navigation("TerritoryType");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.TerritoryAccess", b =>
                {
                    b.HasOne("TerritoryWeb.Data.Models.Territory", "Territory")
                        .WithMany()
                        .HasForeignKey("TerritoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.TerritoryBound", b =>
                {
                    b.HasOne("TerritoryWeb.Data.Models.Territory", "Territory")
                        .WithMany()
                        .HasForeignKey("TerritoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("TerritoryWeb.Data.Models.Congregation", b =>
                {
                    b.Navigation("DoorCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
