// <auto-generated by="the Blazor I18n Text compiler" />
namespace TerritoryWeb.Client.I18nText.Territory
{
    public partial class Details : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Assigned Publisher"</summary>
        public string AssignedPublisher;

        /// <summary>"Checked In"</summary>
        public string CheckedIn;

        /// <summary>"Checked Out"</summary>
        public string CheckedOut;

        /// <summary>"Check In"</summary>
        public string CheckInBtn;

        /// <summary>"Check Out"</summary>
        public string CheckOutBtn;

        /// <summary>"City"</summary>
        public string City;

        /// <summary>"Door Count"</summary>
        public string DoorCount;

        /// <summary>"Doors Details"</summary>
        public string DoorDetails;

        /// <summary>"Last Checked In By"</summary>
        public string LastCheckedInBy;

        /// <summary>"Notes"</summary>
        public string Notes;

        /// <summary>"Details"</summary>
        public string PageTitle;

        /// <summary>"Share Territory"</summary>
        public string ShareTerritoryBtn;

        /// <summary>"View Territory Doors"</summary>
        public string TerritoryDoorBtn;

        /// <summary>"Territory Name"</summary>
        public string TerritoryName;

        /// <summary>"Type"</summary>
        public string Type;
    }
}
