// <auto-generated by="the Blazor I18n Text compiler" />
namespace TerritoryWeb.Client.I18nText.Shared
{
    public partial class Breadcrum : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Home"</summary>
        public string Home;

        /// <summary>"Territory"</summary>
        public string Territory;

        /// <summary>"Create Territory"</summary>
        public string TerritoryCreate;

        /// <summary>"Territory Details"</summary>
        public string TerritoryDetails;

        /// <summary>"Territory Doors"</summary>
        public string TerritoryDoors;
    }
}
