// <auto-generated by="the Blazor I18n Text compiler" />
namespace TerritoryWeb.Client.I18nText.Territory
{
    public partial class Index : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Create Territory"</summary>
        public string CreateTerritory;

        /// <summary>"Territories"</summary>
        public string PageTitle;

        /// <summary>"Assigned Publisher"</summary>
        public string THAssignedPublisher;

        /// <summary>"Checked In"</summary>
        public string THCheckedIn;

        /// <summary>"Checked Out"</summary>
        public string THCheckedOut;

        /// <summary>"City"</summary>
        public string THCity;

        /// <summary>"Doors"</summary>
        public string THDoors;

        /// <summary>"Territory Name"</summary>
        public string THTerritoryName;

        /// <summary>"Type"</summary>
        public string THType;
    }
}
